if (!require("pacman")) install.packages("pacman"); library(pacman)#Load the package manager 
p_load(haven,tidyverse,stats,lmerTest,effects,scales,interactions,apaTables,openxlsx)
setwd("~/Documents/EEOC-AWD")
source("utils.R")
box_data <- "../../Library/CloudStorage/Box-Box/EEOC data/"

#generated by the script: Get Census Data for Merge.ipynb
demo.period <- read.csv(paste0(box_data, "emp_pop_data_05_14.csv")) 
#generated by the script: Clean Raw Data.R
grpd.period <- read.csv(paste0(box_data, "long_annual_claims_dataset.csv"))
#exclude cases that failed to geocode
grpd.period <- grpd.period %>% 
  filter(fixed_fip != "FAILED")
grpd.period <- grpd.period %>% 
  mutate(period = case_when(complaint_year<2010~"0509",#assign claims through 2009 to T1
                            complaint_year>=2010~"1014")) #assign claims after 2009 to T2
table(grpd.period$period,useNA='ifany') 
#aggregate into counties and periods (1 vs. 2)
grpd.wide <- grpd.period %>% 
  group_by(period, fixed_fip) %>% 
  summarise(n.white = sum(n.white,na.rm=T),
            n.race = sum(n.race,na.rm=T),
            n.no.retal = sum(n.no.retal, na.rm=T),
            n.complaints = sum(n.complaints, na.rm=T),
            prop.white.comp = (sum(n.white)/sum(n.no.retal))*100) %>% 
  ungroup() %>% 
  pivot_wider(id_cols=fixed_fip,
              names_from=period,
              values_from=c(n.white, n.race, n.no.retal,n.complaints,prop.white.comp)) %>% 
  #filter out any counties without any claims in time 1 or time 2
  #this is because the outcome variable, a proportion, will be undefined for counties with 0 total claims
  #anything divided by 0 is undefined
  filter(!is.na(n.no.retal_0509)) %>% 
  filter(n.no.retal_0509 != 0) %>% 
  filter(!is.na(n.no.retal_1014)) %>% 
  filter(n.no.retal_1014 != 0)
#get counts of claims
grpd.period %>% 
  group_by(period) %>% 
  summarise(sum(n.no.retal))

demo.period <- demo.period %>% 
  filter(state != 72) %>% 
  mutate(county = str_pad(county, pad="0", side='left',width=3),
         state = str_pad(state, pad='0', side='left',width=2),
         fixed_fip = str_c(state,county))

merged.grp <- left_join(grpd.wide, demo.period, by = "fixed_fip")
#updated ideology dataset: 
#https://dataverse.harvard.edu/file.xhtml?fileId=6690216&version=1.0
ideol <- read_dta(paste0(box_data, "aip_counties_ideology_v2022a.dta"))
ideol["fixed_fip"] <- str_pad(ideol$county_fips, width = 5, side = "left",
                                  pad = "0")
ideol <- ideol %>% 
  filter(survey_period %in% c("2004-2011","2012-2016"))

#there are some "duplicates" that actually have the same information for all columns except democratic vote share
#keep one of the "duplicated" rows since all focal variables are the same across duplicates
dups <- ideol %>% 
  dplyr::group_by(fixed_fip, survey_period) %>%
  dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
  dplyr::filter(n > 1L) 

dup.insp <- ideol %>% filter(fixed_fip %in% dups$fixed_fip)

ideol <- ideol %>% 
  dplyr::group_by(fixed_fip, survey_period) %>% 
  slice(1)
#View(dup.insp)
#grab the conservatism estimates for each county during 2006-2011
ideol.wide <- ideol %>% 
  pivot_wider(id_cols=fixed_fip,
              values_from=mrp_ideology,
              names_from=survey_period)
colnames(ideol.wide) <- c("fixed_fip", "cons_0411", "cons_1216")
merged.att <- left_join(merged.grp, ideol.wide, by = "fixed_fip")
sum(is.na(merged.att$cons_0411))
merged.att <- merged.att %>% 
  filter(!is.na(cons_0411)) 
#merge ideology data with claims and census data
merged.att <- left_join(merged.att,
                        ideol %>% 
                          filter(survey_period=="2004-2011")%>% 
                          select(fixed_fip,demshare_pres),
                        by = "fixed_fip")
merged.att$change.poc.pop <- merged.att$percent_poc_1014 - merged.att$percent_poc_0509
merged.att$change.white.pop <- merged.att$percent_white_1014 - merged.att$percent_white_0509
psych::describe(merged.att$change.white.pop)
hist(merged.att$change.white.pop)
merged.att$sqrt.prop.white_1014 <- sqrt(merged.att$prop.white.comp_1014)

## Descriptives by period

tmp.ideol <- ideol %>% 
  filter(survey_period == "2004-2011")

tmp.demo <- demo.period %>% 
  select(starts_with("total_"), 
         starts_with("white_pop"),
         starts_with("white_unemploy"), 
         fixed_fip)

tmp.poc <- demo.period %>% 
  select(starts_with("percent_poc"),fixed_fip) %>% 
  pivot_longer(cols=starts_with("percent_poc")) %>% 
  rename(percent_poc = value) %>% 
  mutate(period = if_else(str_detect(name, "0509"), "0509", "1014"))
tmp.pop <- demo.period %>% 
  select(starts_with("total_pop"),fixed_fip) %>% 
  pivot_longer(cols=-fixed_fip) %>% 
  rename(total_pop = value) %>% 
  mutate(period = if_else(str_detect(name, "0509"), "0509", "1014"))
tmp.unemp <- demo.period %>% 
  select(starts_with("white_unemp_rate"),fixed_fip) %>% 
  pivot_longer(cols=-fixed_fip) %>% 
  rename(white_unemploy = value) %>% 
  mutate(period = if_else(str_detect(name, "0509"), "0509", "1014"))


grpd.long <- grpd.period %>% 
  group_by(period, fixed_fip) %>% 
  summarise(n.white = sum(n.white,na.rm=T),
            n.race = sum(n.race,na.rm=T),
            n.no.retal = sum(n.no.retal, na.rm=T),
            n.complaints = sum(n.complaints, na.rm=T),
            prop.white.comp = (sum(n.white)/sum(n.no.retal))*100) %>% 
  ungroup()


grpd.long <- left_join(grpd.long, tmp.ideol, by = "fixed_fip")
grpd.long <- left_join(grpd.long, tmp.poc, by = c("fixed_fip","period"))
grpd.long <- left_join(grpd.long, tmp.pop, by = c("fixed_fip","period"))
grpd.long <- left_join(grpd.long, tmp.unemp, by = c("fixed_fip","period"))

### averages
get.cols <- c("n.no.retal", "prop.white.comp", "percent_poc", "total_pop",
              "white_unemploy")
avs <- grpd.long %>% 
  group_by(period) %>% 
  summarise(across(all_of(get.cols),
                   ~str_c(number(mean(.x,na.rm=T),accuracy=.01,big.mark = ","),
                          " (",
                          number(sd(.x, na.rm=T), accuracy = .01,big.mark=","),
                          ")")))

sums <- grpd.long %>% 
  group_by(period) %>% 
  summarise(sum(n.no.retal,na.rm=T),
            sum(n.white,na.rm=T))

psych::describe(merged.att$prop.white.comp_1014)
tmp <- merged.att %>% filter(is.na(prop.white.comp_1014)) #why so much missingness?
orig <- grpd.period %>% filter(fixed_fip %in% tmp$fixed_fip)
View(orig) #it seems like these counties just didn't have any claims in 2010-2014.

#log transform total pop since it's going to be negatively skewed
merged.att$log_total_pop_0509 <- log(merged.att$total_pop_0509)
merged.att$log_total_pop_1014 <- log(merged.att$total_pop_1014)
# plot(merged.att$log_total_pop_0509,merged.att$total_pop_0509)
# plot(merged.att$prop.white.comp_1014,merged.att$sqrt.prop.white_1014)

complete.merge <- merged.att %>% 
  filter(!is.na(prop.white.comp_0509)) %>% 
  filter(!is.na(prop.white.comp_1014)) %>% 
  filter(!is.na(cons_0411)) %>% 
  filter(!is.na(log_total_pop_0509))

hist(merged.att$prop.white.comp_1014)
select.columns <- colnames(complete.merge %>% 
                             select(starts_with("prop.white.comp"), starts_with("log_total_pop"),
                                    starts_with("cons_04"), starts_with("white_unemp_rate"),
                                    starts_with("percent_poc")))
cortab <- apa.cor.table(complete.merge[,select.columns])
cortab <- data.frame(cortab$table.body)
cortab$varname <- str_trim(str_remove_all(cortab$Variable, "\\d[.] "))
cortab <- cortab %>% 
  filter(varname != "")
ranges <- complete.merge %>% 
  summarise(across(all_of(select.columns), 
                   ~str_c(number(min(.x, na.rm=T),accuracy=.01),
                          ", ",
                          number(max(.x, na.rm=T),accuracy=.01))
                   )
            ) %>% 
  pivot_longer(cols = everything()) %>% 
  rename(varname=name,
         range = value)
cortab <- left_join(cortab, ranges, by = "varname")
cortab
write.csv(cortab, "outputs/temporal_cormat.csv")


## TEMPORAL ANALYSIS ---- 
# using pre-Obama-era community characteristics (with caveats for conservatism) to predict Obama-era claim prevalence
test.mod <- lm(prop.white.comp_1014~prop.white.comp_0509+log_total_pop_0509+percent_poc_0509+white_unemp_rate_0509+cons_0411,merged.att);summary(test.mod)
hist(test.mod$residuals)
resid.ut <- test.mod$residuals
test.0 <- lm(sqrt.prop.white_1014~prop.white.comp_0509+log_total_pop_0509+percent_poc_0509+white_unemp_rate_0509+cons_0411,merged.att);summary(test.0)
hist(test.0$residuals)
resid.m1 <- test.0$residuals
resids <- data.frame(resid.ut,
                     resid.m1) %>% 
  pivot_longer(everything())

resid.plots <- resids %>%
  mutate(Outcome = recode(name, 
                          resid.m1 = "Transformed", 
                          resid.ut = "Untransformed")) %>% 
  ggplot(aes(value))+
  geom_histogram(binwidth = .1)+
  facet_wrap(vars(Outcome))+
  labs(x = "Residuals", y = "Frequency", 
       title = "Residual Distribution: Transformed vs. Untransformed Outcome")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        legend.key = element_blank(),
        strip.text.x = element_text(size=12),
        text = element_text(family="Times"),
        axis.text=element_text(size=12),
        title = element_text(size = 10),
        legend.text = element_text(size=12))
resid.plots
#it doesn't seem like the transformation makes a big difference on the normality of the residuals
#they aren't all that normally distributed using the transformed or untransformed variables
summary(test.mod)


test.mod.1 <- lm(prop.white.comp_1014~prop.white.comp_0509+log_total_pop_0509+white_unemp_rate_0509+percent_poc_0509*cons_0411,merged.att)
summary(test.mod.1)

div.levels <- c(mean(merged.att$percent_poc_0509,na.rm=T)-sd(merged.att$percent_poc_0509,na.rm=T),
                mean(merged.att$percent_poc_0509,na.rm=T),
                mean(merged.att$percent_poc_0509,na.rm=T)+sd(merged.att$percent_poc_0509,na.rm=T))
cons.levels <- c(mean(merged.att$cons_0411,na.rm=T)-sd(merged.att$cons_0411,na.rm=T),
                 mean(merged.att$cons_0411,na.rm=T),
                 mean(merged.att$cons_0411,na.rm=T)+sd(merged.att$cons_0411,na.rm=T))
em.obj <- effects::Effect(c('percent_poc_0509','cons_0411'),test.mod.1,
                          xlevels = list(percent_poc_0509=div.levels,
                                         cons_0411 = cons.levels),
                          confint=T)
em.df <- data.frame(em.obj)
em.df %>% 
  mutate(conservatism = case_when(
    cons_0411 < .05~"low",
    cons_0411 >.3 ~"high",
    .default="average"
  )) %>% 
  filter(conservatism != "average") %>% 
  ggplot(aes(x=percent_poc_0509,y = fit, group=conservatism))+
  geom_line(aes(colour=conservatism,linetype=conservatism))+
  geom_ribbon(aes(ymin=lower,ymax=upper),alpha=.1)

sim_slopes(test.mod.1,pred="percent_poc_0509",modx="cons_0411",
           confint = T,digits=3)

test.mod.1a <- lm(prop.white.comp_1014~prop.white.comp_0509+log_total_pop_0509+white_unemp_rate_0509*percent_poc_0509+cons_0411,merged.att)
summary(test.mod.1a)
sim_slopes(test.mod.1a,pred="percent_poc_0509",modx="white_unemp_rate_0509",
           confint = T,digits=3)
unemp.levels <- c(mean(merged.att$white_unemp_rate_0509,na.rm=T)-sd(merged.att$white_unemp_rate_0509,na.rm=T),
                  mean(merged.att$white_unemp_rate_0509,na.rm=T),
                  mean(merged.att$white_unemp_rate_0509,na.rm=T)+sd(merged.att$white_unemp_rate_0509,na.rm=T))
em.obj <- effects::Effect(c('percent_poc_0509','white_unemp_rate_0509'),test.mod.1a,
                          xlevels = list(percent_poc_0509=div.levels,
                                         white_unemp_rate_0509 = unemp.levels),
                          confint=T)
em.df <- data.frame(em.obj)
em.df %>% 
  mutate(white.unemp = case_when(
    white_unemp_rate_0509 < 5~"low",
    white_unemp_rate_0509 >8 ~"high",
    .default="average"
  )) %>% 
  filter(white.unemp != "average") %>% 
  ggplot(aes(x=percent_poc_0509,y = fit, group=white.unemp))+
  geom_line(aes(colour=white.unemp,linetype=white.unemp))+
  geom_ribbon(aes(ymin=lower,ymax=upper),alpha=.1)

test.mod.2 <- lm(prop.white.comp_1014~prop.white.comp_0509+log_total_pop_0509+white_unemp_rate_0509*percent_poc_0509*cons_0411,merged.att)
summary(test.mod.2)
#save df of output for formatting
reg_fmt <- read.csv(paste0("data/","expl_reg_fmt.csv"))
format_regression_table <- function(models){
  tracker = 1
  for(m in models){
    #print(tracker)
    tmp_res = summary(m)
    tmp_coef = data.frame(tmp_res$coefficients)
    tmp_coef[,1] = number(tmp_coef[,1],accuracy = .01)#beta
    tmp_coef[,2] = number(tmp_coef[,2], accuracy = .01)#SE beta
    tmp_coef[,4] = sapply(tmp_coef[,4], statstring::format_sig_stars)#p-val
    tmp_coef[,1] = paste0(tmp_coef[,1], tmp_coef[,4])
    tmp_coef["Predictor"] = rownames(tmp_coef)
    mnum = paste0("model", tracker, "_")
    colnames(tmp_coef) = c(paste0(mnum, c("b", "se_b", "t", "p")), "Predictor")
    tmp_coef = tmp_coef %>% 
      select(Predictor, ends_with("_b"), ends_with("se_b"))
    reg_fmt = left_join(reg_fmt, tmp_coef, by = "Predictor")
    #print(number(statstring::extract_r2(m),accuracy = .001))
    reg_fmt[reg_fmt$Predictor == "R2", paste0(mnum, "se_b")] = number(tmp_res$adj.r.squared,
                                                                      accuracy = .001)
    if(tracker > 1){
      mod_aov = anova(models[[tracker - 1]], models[[tracker]])
      if(is.na(mod_aov$`Pr(>F)`[2])){ #if this is the model with the interaction btwn diversity and white unemployment, compare against model with no interactions
        mod_aov = anova(models[[1]], models[[tracker]])
      }
      print(mod_aov)
      reg_fmt[reg_fmt$Predictor == "Change in R2", 
              paste0(mnum, "se_b")] <- paste0(number(mod_aov$`F`[2], accuracy =.01),
                                              format_sig_stars(mod_aov$`Pr(>F)`[2]))
    }
    tracker = tracker + 1
  }
  reg_fmt[is.na(reg_fmt)] = "-"
  return(reg_fmt)
}

modlist <- list(test.mod,test.mod.1,test.mod.1a,test.mod.2)
reg_out <- format_regression_table(modlist)

write.xlsx(reg_out, paste0("outputs/", "exploratory_time_outs.xlsx"),overwrite = T)
#plot(effects::allEffects(test.mod.2),multline=T)

## robustness--using square-root transformed outcome to improve normality ----
#note that overall results remain the same, but the non-linear transformation of the outcome might make the coefficient for T1 claims difficult to interpret
test.mod.1 <- lm(sqrt.prop.white_1014~prop.white.comp_0509+log_total_pop_0509+white_unemp_rate_0509+percent_poc_0509*cons_0411,merged.att)
summary(test.mod.1)
div.levels <- c(mean(merged.att$percent_poc_0509,na.rm=T)-sd(merged.att$percent_poc_0509,na.rm=T),
                mean(merged.att$percent_poc_0509,na.rm=T),
                mean(merged.att$percent_poc_0509,na.rm=T)+sd(merged.att$percent_poc_0509,na.rm=T))
cons.levels <- c(mean(merged.att$cons_0411,na.rm=T)-sd(merged.att$cons_0411,na.rm=T),
                 mean(merged.att$cons_0411,na.rm=T),
                 mean(merged.att$cons_0411,na.rm=T)+sd(merged.att$cons_0411,na.rm=T))
em.obj <- effects::Effect(c('percent_poc_0509','cons_0411'),test.mod.1,
                          xlevels = list(percent_poc_0509=div.levels,
                                         cons_0411 = cons.levels),
                          confint=T)
em.df <- data.frame(em.obj)
em.df %>% 
  mutate(conservatism = case_when(
    cons_0411 < .05~"low",
    cons_0411 >.3 ~"high",
    .default="average"
  )) %>% 
  ggplot(aes(x=percent_poc_0509,y = fit, group=conservatism))+
  geom_line(aes(colour=conservatism,linetype=conservatism))

plot(effects::allEffects(test.mod.1),multline=T)
p_load(interactions)
sim_slopes(test.mod.1,pred="percent_poc_0509",modx="cons_0411",
           confint = T,digits=3)

test.mod.1a <- lm(sqrt.prop.white_1014~prop.white.comp_0509+log_total_pop_0509+percent_poc_0509*white_unemp_rate_0509+cons_0411,merged.att)
summary(test.mod.1a)
plot(effects::allEffects(test.mod.1a),multline=T)
sim_slopes(test.mod.1a,pred="percent_poc_0509",modx="white_unemp_rate_0509",
           confint = T,digits=3)
unemp.levels <- c(mean(merged.att$white_unemp_rate_0509,na.rm=T)-sd(merged.att$white_unemp_rate_0509,na.rm=T),
                 mean(merged.att$white_unemp_rate_0509,na.rm=T),
                 mean(merged.att$white_unemp_rate_0509,na.rm=T)+sd(merged.att$white_unemp_rate_0509,na.rm=T))
em.obj <- effects::Effect(c('percent_poc_0509','white_unemp_rate_0509'),test.mod.1,
                          xlevels = list(percent_poc_0509=div.levels,
                                         white_unemp_rate_0509 = unemp.levels),
                          confint=T)
em.df <- data.frame(em.obj)
em.df %>% 
  mutate(white.unemp = case_when(
    white_unemp_rate_0509 < 5~"low",
    white_unemp_rate_0509 >8 ~"high",
    .default="average"
  )) %>% 
  filter(white.unemp!="average") %>% 
  ggplot(aes(x=percent_poc_0509,y = fit, group=white.unemp))+
  geom_line(aes(colour=white.unemp,linetype=white.unemp))

test.mod.2 <- lm(sqrt.prop.white_1014~prop.white.comp_0509+log_total_pop_0509+percent_poc_0509*white_unemp_rate_0509*cons_0411,merged.att)
summary(test.mod.2)

## robustness---including 0 counties----
test <- left_join(demo.period, grpd.wide,by='fixed_fip')
test$prop.white.comp_0509[is.na(test$prop.white.comp_0509)] <- 0
test$prop.white.comp_1014[is.na(test$prop.white.comp_1014)] <- 0

test <- left_join(test, ideol.wide,by="fixed_fip")
sum(is.na(test$cons_0411))
test <- test %>% filter(!is.na(cons_0411))#remove cases with missing ideology values
test$log_total_pop_0509 <- log(test$total_pop_0509)

test.mod.1 <- lm(prop.white.comp_1014~prop.white.comp_0509+log_total_pop_0509+white_unemp_rate_0509+percent_poc_0509*cons_0411,test)
summary(test.mod.1)
sim_slopes(test.mod.1,pred="percent_poc_0509",modx="cons_0411",
           confint = T,digits=3)
test.mod.1 <- lm(prop.white.comp_1014~prop.white.comp_0509+log_total_pop_0509+white_unemp_rate_0509*percent_poc_0509+cons_0411,test)
summary(test.mod.1)
sim_slopes(test.mod.1,pred="percent_poc_0509",modx="white_unemp_rate_0509",
           confint = T,digits=3)



